dists:
- distribution: uniform
  'n': 1
  min: 0.2
  max: 0.5
- distribution: uniform
  'n': 1
  min: 0.0
  max: 0.2
within_ranges:
- - 0.22
  - 0.48
- - 0.02
  - 0.18
nrep: 20000
age: 10
proportion: 0.1
nworkers_sim: 3
nworkers_mle: 6
