dists:
- distribution: uniform
  'n': 1
  min: 0.5
  max: 1.0
- distribution: uniform
  'n': 1
  min: 0.0
  max: 0.4
cap_range:
- 10
- 1000
within_ranges:
- - 0.52
  - 0.98
- - 0.02
  - 0.38
- - 100.0
  - 900.0
nrep: 20000
age: 10
ddmodel: 1
proportion: 0.1
nworkers_sim: 4
nworkers_mle: 16
