dists:
- distribution: uniform
  'n': 1
  min: 0.1
  max: 1.0
cap_range:
- 10
- 1000
within_ranges:
- - 0.28
  - 0.82
- - 0.18
  - 0.72
- - 200.0
  - 800.0
nrep: 50000
age: 10
ddmodel: 1
proportion: 0.1
nworkers_sim: 4
nworkers_mle: 16
