dists:
- distribution: uniform
  'n': 1
  min: 0.1
  max: 3.0
cap_range:
- 10
- 1000
max_mu: 0.9
within_ranges:
- - 0.20
  - 1.80
- - 0.18
  - 1.62
- - 100.0
  - 900.0
nrep: 100000
age: 10
ddmodel: 1
proportion: 0.02
nworkers_sim: 6
nworkers_mle: 32
