batch_size_reduce_factor: 0.25
cap_norm_factor: 1000
epoch_number: 21
gcn_layer1_hidden_channels: 256
gcn_layer2_hidden_channels: 128
gcn_layer3_hidden_channels: 64
lin_layer1_hidden_channels: 64
lin_layer2_hidden_channels: 32
min_memory_available: 2147483648
n_optimization_loops: 20
n_predicted_values: 3
n_trials_per_loop: 5
test_batch_size: 64
train_batch_size: 64
