dists:
- distribution: uniform
  'n': 1
  min: 0.1
  max: 4.0
cap_range:
- 10
- 1000
max_mu: 1.5
within_ranges:
- - 0.10
  - 4.00
- - 0.00
  - 1.50
- - 10.0
  - 1000.0
nrep: 100000
age: 10
ddmodel: 1
proportion: 0.02
nworkers_sim: 6
nworkers_mle: 32
