dists:
- distribution: uniform
  'n': 1
  min: 0.1
  max: 1.0
cap_range:
- 10
- 1000
within_ranges:
- - 0.20
  - 0.90
- - 0.10
  - 0.80
- - 100.0
  - 900.0
nrep: 60000
age: 8
ddmodel: 1
proportion: 0.1
nworkers_sim: 4
nworkers_mle: 16
