batch_size_reduce_factor: 0.25
cap_norm_factor: 1000
diffpool_ratio: 0.25
dnn_depth: 5
dnn_hidden_channels: 64
dnn_output_channels: 32
dropout_ratio: 0.5
epoch_number: 31
gcn_layer1_hidden_channels: 256
gcn_layer2_hidden_channels: 128
gcn_layer3_hidden_channels: 64
global_pooling_method: "mean"
huber_delta: 1.0
learning_rate: 0.001
lin_layer1_hidden_channels: 64
lin_layer2_hidden_channels: 32
lstm_depth: 5
lstm_hidden_channels: 64
lstm_output_channels: 32
max_gnn_depth: 6
max_nodes_limit: 2500
n_predicted_values: 3
normalize_edge_length: False
normalize_graph_representation: False
test_batch_size: 64
train_batch_size: 64
