dists_pd:
- distribution: uniform
  'n': 1
  min: 0.2
  max: 0.6
- distribution: uniform
  'n': 1
  min: -0.05
  max: 0.00
- distribution: uniform
  'n': 1
  min: -0.05
  max: 0.05
- distribution: uniform
  'n': 1
  min: 0.00
  max: 0.05
- distribution: uniform
  'n': 1
  min: -0.002
  max: 0.002
dists_ed:
- distribution: uniform
  'n': 1
  min: 0.2
  max: 0.6
- distribution: uniform
  'n': 1
  min: -0.05
  max: 0.00
- distribution: uniform
  'n': 1
  min: -0.05
  max: 0.05
- distribution: uniform
  'n': 1
  min: 0.00
  max: 0.05
- distribution: uniform
  'n': 1
  min: -0.002
  max: 0.002
dists_nnd:
- distribution: uniform
  'n': 1
  min: 0.2
  max: 0.6
- distribution: uniform
  'n': 1
  min: -0.05
  max: 0.00
- distribution: uniform
  'n': 1
  min: -0.05
  max: 0.05
- distribution: uniform
  'n': 1
  min: 0.00
  max: 0.05
- distribution: uniform
  'n': 1
  min: -0.002
  max: 0.002
within_ranges_pd:
- - 0.44
  - 0.76
- - 0.04
  - 0.60
- - -0.045
  - 0.0024
- - -0.045
  - 0.0024
within_ranges_ed:
- - 0.44
  - 0.76
- - 0.04
  - 0.60
- - -0.045
  - 0.0016
- - -0.045
  - 0.0016
within_ranges_nnd:
- - 0.33
  - 0.57
- - 0.03
  - 0.45
- - -0.045
  - 0.0008
- - -0.045
  - 0.0008
nrep: 80000
age: 10
nworkers_sim: 24
