dists_pd:
- distribution: uniform
  'n': 1
  min: 0.4
  max: 1.0
- distribution: uniform
  'n': 1
  min: 0.0
  max: 0.4
- distribution: uniform
  'n': 1
  min: -0.1
  max: 0.01
- distribution: uniform
  'n': 1
  min: -0.1
  max: 0.01
dists_ed:
- distribution: uniform
  'n': 1
  min: 0.4
  max: 0.8
- distribution: uniform
  'n': 1
  min: 0.0
  max: 0.4
- distribution: uniform
  'n': 1
  min: -0.1
  max: 0.01
- distribution: uniform
  'n': 1
  min: -0.1
  max: 0.01
dists_nnd:
  - distribution: uniform
    'n': 1
    min: 0.3
    max: 0.6
  - distribution: uniform
    'n': 1
    min: 0.0
    max: 0.3
  - distribution: uniform
    'n': 1
    min: -0.1
    max: 0.01
  - distribution: uniform
    'n': 1
    min: -0.1
    max: 0.01
within_ranges_pd:
- - 0.42
  - 0.98
- - 0.02
  - 0.38
- - -0.08
  - 0.008
- - -0.08
  - 0.008
within_ranges_ed:
- - 0.42
  - 0.78
- - 0.02
  - 0.38
- - -0.08
  - 0.008
- - -0.08
  - 0.008
within_ranges_nnd:
- - 0.32
  - 0.58
- - 0.02
  - 0.28
- - -0.08
  - 0.008
- - -0.08
  - 0.008
nrep: 20000
age: 8
nworkers_sim: 8
