dists_pd:
- distribution: uniform
  'n': 1
  min: 0.4
  max: 0.6
- distribution: uniform
  'n': 1
  min: 0
  max: 0.2
- distribution: uniform
  'n': 1
  min: -0.05
  max: 0.00
- distribution: uniform
  'n': 1
  min: -0.05
  max: 0.05
- distribution: uniform
  'n': 1
  min: 0.00
  max: 0.05
- distribution: uniform
  'n': 1
  min: -0.002
  max: 0.002
dists_ed:
- distribution: uniform
  'n': 1
  min: 0.4
  max: 0.6
- distribution: uniform
  'n': 1
  min: 0
  max: 0.2
- distribution: uniform
  'n': 1
  min: -0.05
  max: 0.00
- distribution: uniform
  'n': 1
  min: -0.05
  max: 0.05
- distribution: uniform
  'n': 1
  min: 0.00
  max: 0.05
- distribution: uniform
  'n': 1
  min: -0.002
  max: 0.002
dists_nnd:
- distribution: uniform
  'n': 1
  min: 0.4
  max: 0.6
- distribution: uniform
  'n': 1
  min: 0
  max: 0.2
- distribution: uniform
  'n': 1
  min: -0.05
  max: 0.00
- distribution: uniform
  'n': 1
  min: -0.05
  max: 0.05
- distribution: uniform
  'n': 1
  min: 0.00
  max: 0.05
- distribution: uniform
  'n': 1
  min: -0.002
  max: 0.002
nrep: 50000
age: 10
nworkers_sim: 24
