dists:
  - distribution: uniform
    'n': 1
    min: 0.1
    max: 2.0
  - distribution: log10
    'n': 1
    min: 0.001
    max: 10
  - distribution: uniform
    'n': 1
    min: 0.1
    max: 2.0
max_mu: 1.0
within_ranges:
  - - 0.10
    - 2.00
  - - 0.001
    - 10
  - - 0.10
    - 2.00
  - - 0.0
    - 1.0
  - - 0.0
    - 1.0
nrep: 100000
age: 10
proportion: 0.05
nworkers_sim: 6
nworkers_mle: 16
