dists:
  - distribution: uniform
    'n': 1
    min: 0.1
    max: 1.0
  - distribution: log10
    'n': 1
    min: 0.001
    max: 10
  - distribution: uniform
    'n': 1
    min: 0.1
    max: 1.0
max_mu1: 0.8
max_mu2: 0.8
within_ranges:
  - - 0.10
    - 1.00
  - - 0.001
    - 10
  - - 0.10
    - 1.00
  - - 0.0
    - 0.8
  - - 0.0
    - 0.8
nrep: 100000
age: 10
proportion: 0.02
nworkers_sim: 6
nworkers_mle: 8
