dists:
  - distribution: uniform
    'n': 1
    min: 0.1
    max: 0.8
  - distribution: uniform
    'n': 1
    min: 0.5
    max: 1.0
  - distribution: uniform
    'n': 1
    min: 0.1
    max: 0.8
within_ranges:
  - - 0.24
    - 0.66
  - - 0.60
    - 0.90
  - - 0.24
    - 0.66
  - - 0.128
    - 0.512
  - - 0.128
    - 0.512
nrep: 60000
age: 8
proportion: 0.1
nworkers_sim: 6
nworkers_mle: 16
