dists:
  - distribution: uniform
    'n': 1
    min: 0.1
    max: 0.8
  - distribution: uniform
    'n': 1
    min: 0.5
    max: 1.0
  - distribution: uniform
    'n': 1
    min: 0.1
    max: 0.8
within_ranges:
  - - 0.18
    - 0.72
  - - 0.55
    - 0.95
  - - 0.18
    - 0.72
  - - 0.060
    - 0.580
  - - 0.060
    - 0.580
nrep: 60000
age: 8
proportion: 0.1
nworkers_sim: 6
nworkers_mle: 16
