dists:
  - distribution: uniform
    'n': 1
    min: 0.1
    max: 0.8
  - distribution: uniform
    'n': 1
    min: 0.001
    max: 10
  - distribution: uniform
    'n': 1
    min: 0.1
    max: 0.8
within_ranges:
  - - 0.18
    - 0.72
  - - 0.002
    - 5
  - - 0.18
    - 0.72
  - - 0.060
    - 0.580
  - - 0.060
    - 0.580
nrep: 60000
age: 10
proportion: 0.1
nworkers_sim: 6
nworkers_mle: 16
