install.packages("yaml")
remotes::install_github("YuLab-SMU/ggtree", force = TRUE)
remotes::install_github("thijsjanzen/treestats", force = TRUE)
remotes::install_github("EvoLandEco/eve", force = TRUE)
remotes::install_github("EvoLandEco/eveGNN", force = TRUE)